/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGRPC_H_RPCGEN
#define _LOGRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct log_arg {
	char username[256];
	char operation[32];
	char filename[256];
};
typedef struct log_arg log_arg;

#define LOG 100522214
#define LOG_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_log 1
extern  enum clnt_stat rpc_log_1(log_arg , int *, CLIENT *);
extern  bool_t rpc_log_1_svc(log_arg , int *, struct svc_req *);
extern int log_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_log 1
extern  enum clnt_stat rpc_log_1();
extern  bool_t rpc_log_1_svc();
extern int log_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_arg (XDR *, log_arg*);

#else /* K&R C */
extern bool_t xdr_log_arg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGRPC_H_RPCGEN */
