/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "logRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpc_log_1(log_arg arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_log,
		(xdrproc_t) xdr_log_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
